version: '3.4'

services:
  github_io_page:
    image: ${DOCKER_REGISTRY-}github_io_page
    build:
      context: .
      dockerfile: github_io_page/Dockerfile
    container_name: github_io_page_app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: github_io_page
      MYSQL_USER: blazortemplate
      MYSQL_PASSWORD: blazortemplate123
    volumes:
      - github_io_page-data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: blazor_mysql_db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: blazortemplate
      PMA_PASSWORD: blazortemplate123
    ports:
      - "8080:80"
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db

volumes:
  github_io_page-data:
